#!/usr/bin/env powershell
# Setup Discord Dependencies - PowerShell Edition
# Final solution for installing @discordjs packages

# Set error handling to stop on first error
`$ErrorActionPreference = "Stop"`

Write-Host '=== Discord Dependencies Setup ===' -ForegroundColor Green
Write-Host 'Fixing Discord.js packages for current Node.js version' -ForegroundColor Yellow
Write-Host 'Current Node.js version: ' + (node --version) -ForegroundColor Cyan

# Step 1: Clean up existing problematic packages
Write-Host "Cleaning up old Discord.js packages..." -ForegroundColor Yellow
try {
    `npm uninstall @discordjs/voice @discordjs/opus discord.js libsodium-wrappers 2>`
    Write-Host "✅ Old packages removed" -ForegroundColor Green
} catch {
    Write-Host "⚠️ Could not remove all packages (this may be normal)" -ForegroundColor Yellow
}

# Step 2: Install the actual available packages
Write-Host "`nInstalling Discord.js packages..." -ForegroundColor Green
Write-Host "Installing @discordjs/voice=0.19.2..." -ForegroundColor Cyan
Write-Host "Installing @discordjs/opus=0.10.0..." -ForegroundColor Cyan
Write-Host "Installing @discordjs/node-pre-gyp=0.10.0..." -ForegroundColor Cyan
Write-Host "Installing discord.js=14.21.1..." -ForegroundColor Cyan
Write-Host "Installing libsodium-wrappers=0.11.0..." -ForegroundColor Cyan

`$installCommand = 'npm install @discordjs/voice=0.19.2 @discordjs/opus=0.10.0 @discordjs/node-pre-gyp@0.10.0 discord.js=14.21.1 libsodium-wrappers=0.11.0 --legacy-peer-deps'
Write-Host "Running: `$installCommand" -ForegroundColor White
`$result = iex `$installCommand`

if (`$LASTEXITCODE -eq 0`) {
    Write-Host "`n✅ Discord dependencies installed successfully!" -ForegroundColor Green
    Write-Host "The project is now compatible with current Node.js version" -ForegroundColor Green
    
    # Create run script
    `$runScript = @`
@REM Discord Synth Bot Development Environment
@REM Compatible with Node.js 24+
@REM Generated by setup script

@echo off
cd /d %~dp0
set NODE_ENV=development

echo ==========================================
echo Discord Synth Bot - Enhanced Setup
echo ==========================================
echo.
echo Starting Discord services...
echo This will launch:
echo   - Discord bot (connects to Discord with voice support)
echo   - Web API server (REST endpoints)
echo   - WebSocket server (real-time synchronization)
echo   - Web UI (React application)
echo.
echo To run individual services:
echo   dev:bot    (Discord bot only)
echo   dev:web    (Web server only)
echo   dev:ui     (Web UI only)
echo.
echo To run all services together:
echo   npm run dev

echo.
pause >nul
'@n
    `$runScript | Out-File -FilePath '%~dp0\RUN_SETUP.bat' -Encoding ASCII`
    Write-Host "✅ Created RUN_SETUP.bat" -ForegroundColor Green
    Write-Host "`n=== Setup Complete ===" -ForegroundColor Green
    Write-Host "Run RUN_SETUP.bat to start the development environment" -ForegroundColor Yellow
} else {
    Write-Host "`n❌ Discord dependency installation failed" -ForegroundColor Red
    Write-Host "Check npm output for specific errors" -ForegroundColor Red
    exit 1
}